toxicsearch/urls.py
from django.urls import path
from . import views

app_name = 'toxicsearch'
urlpatterns = [
    path('', views.index_view, name="home"),
    path('search/', views.search_view, name='search'),
    path('updatedb', views.update_db, name="updatedb"),
    path('update_movies/', views.update_movies_table, name="movies_update"),
    path('update_series/', views.update_series_table, name="series_update"),
]

handler404 = 'toxicsearch.views.handler404'
import toxicsearch.scheduler  # NOQA @isort:skip
import logging
logging.basicConfig(level="DEBUG")

tsearch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('toxicsearch.urls'))
]

toxicsearch/models.py
from django.db import models


class Movie(models.Model):
    movie_title = models.CharField(max_length=255)
    movie_link = models.URLField()

    def __str__(self):
        return self.movie_title


class Series(models.Model):
    series_title = models.CharField(max_length=255)
    series_link = models.URLField()

    def __str__(self):
        return self.series_title

    class Meta:
        verbose_name_plural = "Series"

toxicsearch/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=255, min_length=2, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'search',
                                                                                                'placeholder': 'search for items here...'}))

toxicsearch/views.py
from django.shortcuts import render, redirect
from .forms import SearchForm

from .models import Movie, Series
from .tasks import Thread
from .scrape import should_be_added


def index_view(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
    else:
        form = SearchForm
        context = {
            'form': form
        }
    return render(request=request, template_name='toxicsearch/index.html', context=context)


def search_view(request):
    if request.method == "POST":
        movies_in_db = Movie.objects.all()
        series_in_db = Series.objects.all()
        form = SearchForm(request.POST)
        if form.is_valid():
            search = form.cleaned_data['search']
            movies = []
            series = []
            for movie in movies_in_db:
                if should_be_added(search, movie.movie_title):
                    movies.append(movie)
            for serie in series_in_db:
                if should_be_added(search, serie.series_title):
                    series.append(serie)
    else:
        form = SearchForm
        movies = []
        series = []
    context = {
        'form': form,
        'movies': movies,
        'series': series
    }
    return render(request=request, template_name='toxicsearch/results.html', context=context)


def update_db(request):
    thread_for_movies = Thread()
    thread_for_series = Thread()
    thread_for_movies.start()
    thread_for_series.start()
    thread_for_series.add_series_to_database()
    thread_for_movies.add_series_to_database()
    return redirect('/')


def update_movies_table(request):
    thread = Thread()
    thread.start()
    thread.add_movies_to_database()
    return redirect('/')


def update_series_table(request):
    thread = Thread()
    thread.start()
    thread.add_series_to_database()
    return redirect('/')


def handler404(request, exception):
    return render(request=request, template_name='404.html')

toxicsearch/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <script src="https://kit.fontawesome.com/4850730013.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/index.css'%}" />
    <title>Tsearch|results</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-end">
      <a href="{% url 'toxicsearch:home' %}" class="navbar-brand"
        >Tsearch<i class="fas fa-search" id="logo-icon"></i
      ></a>
        <div class="nav-item ml-auto mr-1">
      <a class="nav-item ml-auto mr-1">{% if request.user.is_superuser%}
          <button class="btn btn-success"> <a href="{% url 'toxicsearch:movies_update' %}" >Fetch movies</a>
          </button>{% endif%}</a>
       <a class="nav-item ml-auto mr-1">{% if request.user.is_superuser%}
          <button class="btn btn-success"> <a href="{% url 'toxicsearch:series_update' %}" >Fetch Series</a>
          </button>{% endif%}</a>
            <a class="nav-item ml-auto mr-1">{% if request.user.is_superuser%}<button class="btn btn-success">
          <a href="{% url 'toxicsearch:updatedb' %}" >Fetch all</a></button>{% endif%}</a>
            </div>
    </nav>
  {% block main_content %}

    {% endblock main_content %}


     <footer><div id="footer-copywrite"></div></footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
  </body>
</html>

toxicsearch/templates/toxicsearch/index.html
{% extends 'base.html' %}

{% block main_content %}

{% load static %}
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center" id="main-heading">
            Search Toxicwap for Movies, TV series and Cartoons
          </h1>
        </div>
      </div>
      <div class="row mt-1">&nbsp;</div>
      <div class="row">
        <div class="col-md-12" id="search-form">
          <form method="POST" action="{% url 'toxicsearch:search' %}">
            {% csrf_token %}
            <div class="d-table-cell w-100">
             {{ form.search}}
            </div>
            <div class="d-table-cell align-middle">
              <button id="search-btn" class="btn btn-success">
                <i class="fas fa-search" id="search-icon"></i>
              </button>
            </div>
          </form>
        </div>
      </div>
      <div class="row mt-3">&nbsp;</div>

      <div class="row">
        <div class="col-md-4 col-sm-4 text-center" id="promo-row">
          <i class="fas fa-search fa-5x"></i>
          <p class="lead">
            Search for Movies, Tv series and Cartoons
            place.
          </p>
        </div>
        <div class="col-md-4 col-sm-4 text-center" id="promo-row">
          <i class="fas fa-clone fa-5x"></i>
          <p class="lead">
            Compare different movies and series
          </p>
        </div>
        <div class="col-md-4 col-sm-4 text-center" id="promo-row">
          <i class="fas fa-filter fa-5x"></i>
          <p class="lead">
            Filter the search results so that you can easily find what you are
            looking for.
          </p>
        </div>
      </div>
    </div>

{% endblock main_content %}

toxicsearch/templates/toxicsearch/results.html
{% extends 'base.html' %}


{% block main_content %}
    <div class="container">
      <div class="row mt-3"></div>
      <div class="row">
        <div class="col-md-12" id="search-form">
         <form method="POST" action="{% url 'toxicsearch:search' %}">
            {% csrf_token %}
            <div class="d-table-cell w-100">
             {{ form.search}}
            </div>
            <div class="d-table-cell align-middle">
              <button id="search-btn" class="btn btn-success">
                <i class="fas fa-search" id="search-icon"></i>
              </button>
            </div>
          </form>
        </div>
      </div>

      <div class="row" id="results-row">
        <div class="col-md-12">
          <ul
            class="nav nav-tabs mb-3 mt-3 nav-justified"
            id="pills-tab"
            role="tablist"
          >
            <li class="nav-item">
              <a
                class="nav-link active"
                id="pills-home-tab"
                data-toggle="tab"
                href="#tabs-movies"
                role="tab"
                aria-controls="pills-home"
                aria-selected="true"
                >Movies</a
              >
            </li>

            <li class="nav-item">
              <a
                class="nav-link"
                id="pills-profile-tab"
                data-toggle="tab"
                href="#tabs-tv-series"
                role="tab"
                aria-controls="pills-profile"
                aria-selected="false"
                >TV Series</a
              >
            </li>

          </ul>

          <div class="tab-content" id="pills-tabContent">
            <div
              class="tab-pane fade show active"
              id="tabs-movies"
              role="tabpanel"
              aria-labelledby="pills-movies-tab"
            >
              {% if movies %}
              <ul class="list-group">
                {% for movie in movies %}
                <li class="list-group-item">
                  <a href="{{movie.movie_link}}" target="_blank">{{movie.movie_title}}</a>

                </li>
                {% endfor %}
              </ul>
              {% else %}
              <h2 class="text-danger"> No movies found for that search term</h2>
              {% endif %}
            </div>

            <div
              class="tab-pane fade"
              id="tabs-tv-series"
              role="tabpanel"
              aria-labelledby="pills-contact-tab"
            >
              {% if series %}
               <ul class="list-group">
                {% for serie in series %}
                <li class="list-group-item">
                  <a href="{{serie.series_link}}" target="_blank">{{serie.series_title}}</a>

                </li>
                {% endfor %}
              </ul>
              {% else %}
              <h2 class="text-danger">No series found for that search term</h2>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock main_content %}